"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class new_test_message(object):
    __slots__ = ["coord_x", "coord_y", "coord_z"]

    __typenames__ = ["double", "double", "double"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.coord_x = 0.0
        self.coord_y = 0.0
        self.coord_z = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(new_test_message._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.coord_x, self.coord_y, self.coord_z))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != new_test_message._get_packed_fingerprint():
            raise ValueError("Decode error")
        return new_test_message._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = new_test_message()
        self.coord_x, self.coord_y, self.coord_z = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if new_test_message in parents: return 0
        tmphash = (0x898aa800298fb1be) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if new_test_message._packed_fingerprint is None:
            new_test_message._packed_fingerprint = struct.pack(">Q", new_test_message._get_hash_recursive([]))
        return new_test_message._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

